extends RichTextLabel

func _ready():
	text = """
[bgcolor=green][color=black]WELCOME TO 'HUNT THE SNARF'[/color][/bgcolor]

'HUNT THE SNARF' REIMAGINES CLASSIC TEXT-BASED ADVENTURES
LIKE 'HUNT THE WUMPUS' IN A MODERN CONTEXT, WHERE PLAYERS
NAVIGATE A MAZE INSPIRED BY SOCIAL MEDIA DYNAMICS.

THE WUMPUS LIVES IN A SITE OF 20 PAGES. EACH PAGE
HAS 3 CONNECTIONS LEADING TO OTHER PAGES. (LOOK AT A
DODECAHEDRON TO SEE HOW THIS WORKS - IF YOU DON'T KNOW
WHAT A DODECAHEDRON IS, ASK SOMEONE)

[bgcolor=green][color=black]HAZARDS:[/color][/bgcolor]

  [bgcolor=green][color=black]CLICKBAIT LOOPS[/color][/bgcolor] - TWO PAGES HAVE CLICKBAIT LOOPS IN THEM.
	IF YOU GO THERE, YOU GET LOST IN THE LOOP (& LOSE!)
  [bgcolor=green][color=black]VIRAL STORMS[/color][/bgcolor] - TWO OTHER PAGES HAVE VIRAL STORMS. IF YOU
	GO THERE, A STORM TAKES YOU TO SOME OTHER
	PAGE AT RANDOM (WHICH MIGHT BE TROUBLESOME).

[bgcolor=green][color=black]SNARF:[/color][/bgcolor]

  THE SNARF IS NOT BOTHERED BY THE HAZARDS (HE IS AN AI
AFTER ALL). USUALLY HE IS ASLEEP.

  TWO THINGS WAKE HIM UP: YOUR ENTERING HIS PAGE OR
YOUR SHOOTING A BOLT.

  IF THE SNARF WAKES, HE MOVES (P=.75) ONE PAGE
OR STAYS STILL (P=.25). AFTER THAT, IF HE IS WHERE YOU
ARE, HE EATS YOU UP (& YOU LOSE!)

[bgcolor=green][color=black]YOU:[/color][/bgcolor]

  EACH TURN YOU MAY MOVE OR SHOOT A CRITICAL THINKING BOLT
	[bgcolor=green][color=black]MOVING[/color][/bgcolor]: YOU CAN GO ONE PAGE (THRU ONE CONNECTION)
	[bgcolor=green][color=black]BOLTS[/color][/bgcolor]: YOU HAVE 5 BOLTS. YOU LOSE WHEN YOU RUN OUT.
  EACH BOLT CAN GO FROM 1 TO 5 PAGES. YOU AIM BY TELLING
  THE COMPUTER THE PAGE NUMBERS YOU WANT THE BOLT TO HIT.
  IF THE BOLT CAN'T GO THAT WAY (IE NO CONNECTION) IT MOVES
  AT RAMDOM ONTO THE NEXT PAGE.

  IF THE BOLT HITS THE SNARF, YOU WIN.

  IF THE BOLT HITS YOU, YOU LOSE.

[bgcolor=green][color=black]WARNINGS:[/color][/bgcolor]

  WHEN YOU ARE ONE PAGE AWAY FROM SNARF OR HAZARD,
  THE COMPUTER SAYS:
	[bgcolor=green][color=black]SNARF[/color][/bgcolor]          - 'IT SMELLS LIKE SNARF CODE'
	[bgcolor=green][color=black]CLICKBAIT LOOP[/color][/bgcolor] - 'I HEAR CLICKS'
	[bgcolor=green][color=black]VIRAL STORM[/color][/bgcolor]    - 'I FEEL ENGAGEMENT'
"""
